#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : mvn-rhino
Version  : 1.7.7
Release  : 1
URL      : https://repo1.maven.org/maven2/org/mozilla/rhino/1.7.7/rhino-1.7.7.jar
Source0  : https://repo1.maven.org/maven2/org/mozilla/rhino/1.7.7/rhino-1.7.7.jar
Source1  : https://repo1.maven.org/maven2/org/mozilla/rhino/1.7.7/rhino-1.7.7.pom
Source2  : https://repo1.maven.org/maven2/org/mozilla/rhino/1.7R3/rhino-1.7R3.jar
Source3  : https://repo1.maven.org/maven2/org/mozilla/rhino/1.7R3/rhino-1.7R3.pom
Summary  : No detailed summary available
Group    : Development/Tools
License  : GPL-2.0 MPL-1.1 MPL-2.0
Requires: mvn-rhino-data = %{version}-%{release}

%description
No detailed description available

%package data
Summary: data components for the mvn-rhino package.
Group: Data

%description data
data components for the mvn-rhino package.


%prep
%setup -q -n META-INF

%build

%install
mkdir -p %{buildroot}/usr/share/java/.m2/repository/org/mozilla/rhino/1.7.7
cp %{SOURCE0} %{buildroot}/usr/share/java/.m2/repository/org/mozilla/rhino/1.7.7/rhino-1.7.7.jar

mkdir -p %{buildroot}/usr/share/java/.m2/repository/org/mozilla/rhino/1.7.7
cp %{SOURCE1} %{buildroot}/usr/share/java/.m2/repository/org/mozilla/rhino/1.7.7/rhino-1.7.7.pom

mkdir -p %{buildroot}/usr/share/java/.m2/repository/org/mozilla/rhino/1.7R3
cp %{SOURCE2} %{buildroot}/usr/share/java/.m2/repository/org/mozilla/rhino/1.7R3/rhino-1.7R3.jar

mkdir -p %{buildroot}/usr/share/java/.m2/repository/org/mozilla/rhino/1.7R3
cp %{SOURCE3} %{buildroot}/usr/share/java/.m2/repository/org/mozilla/rhino/1.7R3/rhino-1.7R3.pom


%files
%defattr(-,root,root,-)

%files data
%defattr(-,root,root,-)
/usr/share/java/.m2/repository/org/mozilla/rhino/1.7.7/rhino-1.7.7.jar
/usr/share/java/.m2/repository/org/mozilla/rhino/1.7.7/rhino-1.7.7.pom
/usr/share/java/.m2/repository/org/mozilla/rhino/1.7R3/rhino-1.7R3.jar
/usr/share/java/.m2/repository/org/mozilla/rhino/1.7R3/rhino-1.7R3.pom
